// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Ly-GGL0tFhLQQFVP4s4NQH4Biv-x73s',
    appId: '1:645295786932:web:c25731abd7c88f321dc0e1',
    messagingSenderId: '645295786932',
    projectId: 'pushnotfication-7ac78',
    authDomain: 'pushnotfication-7ac78.firebaseapp.com',
    storageBucket: 'pushnotfication-7ac78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC507hX8qMfqAOX9EZdeDlj3LzBo7H-Jo4',
    appId: '1:645295786932:android:a20e061edcd82b951dc0e1',
    messagingSenderId: '645295786932',
    projectId: 'pushnotfication-7ac78',
    storageBucket: 'pushnotfication-7ac78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNBHqVGcZodDJ3kCd_FgTBI52fSSkN4I',
    appId: '1:645295786932:ios:a3d04d645582a7aa1dc0e1',
    messagingSenderId: '645295786932',
    projectId: 'pushnotfication-7ac78',
    storageBucket: 'pushnotfication-7ac78.appspot.com',
    iosBundleId: 'com.example.nunaTechCodeChallange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNBHqVGcZodDJ3kCd_FgTBI52fSSkN4I',
    appId: '1:645295786932:ios:a3d04d645582a7aa1dc0e1',
    messagingSenderId: '645295786932',
    projectId: 'pushnotfication-7ac78',
    storageBucket: 'pushnotfication-7ac78.appspot.com',
    iosBundleId: 'com.example.nunaTechCodeChallange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Ly-GGL0tFhLQQFVP4s4NQH4Biv-x73s',
    appId: '1:645295786932:web:a428d55ceab7d6271dc0e1',
    messagingSenderId: '645295786932',
    projectId: 'pushnotfication-7ac78',
    authDomain: 'pushnotfication-7ac78.firebaseapp.com',
    storageBucket: 'pushnotfication-7ac78.appspot.com',
  );
}
